CREATE TABLE TEXT_COURSE (
	code 			VARCHAR(20) NOT NULL,
	title			VARCHAR(50) NOT NULL,
	description		VARCHAR(255) NOT NULL
);

ALTER TABLE TEXT_COURSE ADD CONSTRAINT PK_TEXT_COURSE PRIMARY KEY (code);
