CREATE TABLE TEXT_STUDENT_COURSE (
	student_id	 	INT NOT NULL,
	course_code		VARCHAR(20) NOT NULL
);

ALTER TABLE TEXT_STUDENT_COURSE ADD CONSTRAINT PK_TEXT_STUDENT_COURSE PRIMARY KEY (student_id, course_code);

ALTER TABLE TEXT_STUDENT_COURSE ADD CONSTRAINT FK1_TEXT_STUDENT_COURSE FOREIGN KEY (student_id) REFERENCES TEXT_STUDENT(id);

ALTER TABLE TEXT_STUDENT_COURSE ADD CONSTRAINT FK2_TEXT_STUDENT_COURSE FOREIGN KEY (course_code) REFERENCES TEXT_COURSE(code);

